### ISSUE TITLE
Improving error messages: When Elm is not found

### ISSUE THREAD

**Issue by jwoLondon** [gicentre/litvis#11]
If there has been a problem installing Elm as part of Litvis, trying to preview a litvis document that contains some elm generates this error message:

    spawn elm ENOENT (litvis:elmp-environment)

We should replace this with a more friendly message, especially as this is most likely to occur when using Litvis for the first time. I suggest

    I am having trouble finding Elm on your machine. Is it installed? Check by opening a terminal window and typing "elm --version" (without quotation marks). If you have recently installed Elm, try restarting your machine.

**Comment by kachkaev** [comment]
As it turns out, I’ve already had a mechanism of expiring working directories with temporary elm projects. This issue should be fixed now on master and will be available to users with the next release.
