### ISSUE TITLE
No output of tuples in raw mode

### ISSUE THREAD

**Issue by jwoLondon** [gicentre/litvis#13]
See also related issue #14 

Just so we have a record of it, currently, when setting a code block to `raw` / `r`, tuples are not displayed. 

Minimal working example:

````
```elm {r}
tupleTest : ( Int, Int )
tupleTest =
    ( 99, 50 )
```
````

Should display `(99,50)` but nothing is displayed, nor is any warning generated.

The same problem occurs with a list of tuples:

````
```elm {r}
tupleListTest : List ( Int, Int )
tupleListTest =
    [ ( 1, 2 ), ( 3, 4 ) ]
```
````

Interestingly, if a tuple or list of tuples is embedded inside a record, it is displayed correctly, which may help to diagnose the cause of the problem:

````
```elm {r}
type alias MyRecord =
    { intItem : Int
    , strItem : String
    , booItem : Bool
    , lstItem : List Int
    , tplItem : ( Int, Int )
    , tp3Item : ( Bool, Int, String )
    , tLsItem : List ( Int, Int )
    , rcdItem : { nestedName : String, nestedValue : Int }
    }


recordTest : MyRecord
recordTest =
    MyRecord 1 "two" True [ 3, 4, 5 ] ( 6, 7 ) ( False, 8, "nine" ) [ ( 10, 11 ), ( 12, 13 ) ] { nestedName = "fourteen", nestedValue = 15 }
```
````

Generated the following (correct) raw output:

`{ booItem = True, intItem = 1, lstItem = [3,4,5], rcdItem = { nestedName = "fourteen", nestedValue = 15 }, strItem = "two", tLsItem = [(10,11),(12,13)], tp3Item = (False,8,"nine"), tplItem = (6,7) }[(1,2),(3,4)]`

**Comment by jwoLondon** [comment]
In case it helps with the regexp, tuples can have only two or three elements as of Elm 0.19. 4-tuples or longer are no longer permitted.

**Comment by kachkaev** [comment]
Your examples above worked after I fixed https://github.com/gicentre/litvis/issues/14 🎉
