### ISSUE TITLE
Records not displayed in raw mode if type annotation uses literal record

### ISSUE THREAD

**Issue by jwoLondon** [gicentre/litvis#14]
See also related issue #13

If an Elm record is declared in a function with a type alias for the record in the type annotation, it is displayed as expected:

````
```elm {r}
type alias MySimpleRecord =
    { name : String }


recordTest1 : MySimpleRecord
recordTest1 =
    { name = "hello" }

````

(generates correct output of `{ name = "hello" }` )

But if an anonymous declaration (i.e. not using a named type alias) is used in the type annotation, it is not displayed:

````
```elm {r}
recordTest2 : { name : String }
recordTest2 =
    { name = "hello" }
```
````
(it should be noted this is a perfectly legal construct in Elm)

If it is not straightforward to detect record types in type annotations for raw output, we should probably at least generate a warning.

**Comment by jwoLondon** [comment]
I think we should be safe from false positives if we ensure the regex requires a single `:` as this cannot be used for anything other than type annotation (and in quoted text strings). I'm not sure your more relaxed regex captures all valid annotations though.

Here are a few valid type annotations to test:

```elm
fn1 : List ( Int, Int )
fn2 : ( ( Int, Int ), ( String, String ) )
fn3 : { x : Int }
fn4 : ( Int, String )
fn5 : List (List ( Int, Int ))
fn6 : List { x : Int }
fn7 : List (List { x : Int })
fn8 : ( Int, List (List { x : Int }) )
fn9 : MyTypeAlias
```

**Comment by jwoLondon** [comment]
Note the possibility of false positives in multiline text (both anchored at the start of a line and the embedding quotes appear on separate lines: #16

**Comment by kachkaev** [comment]
The proposed regexp "cuts" at the first `:` and only requires alphanumeric chars before it. Characters following `:` do not matter (see no `$` in the end of regexp, which means that it does not apply to the whole row). This means that even this will pass:

```elm
fn4 : (
Int, String
)
```

(not sure if it's a valid Elm though)

As long as `something :` with no leading spaces can only indicate a symbol, we'e good. Things will get a bit trickier if it's allowed to write:

```elm
fn3 : {
x : Int
}
```

**Comment by jwoLondon** [comment]
No, neither of those are valid elm (which is good), because elm requires type annotations to be on a single line. That should help constrain the pattern matching required. Also, elm-format / prettier will do its best to move the type annotation onto a single line if it is split, which also helps us.
