### ISSUE TITLE
Siding generates incorrect missing symbol

### ISSUE THREAD

**Issue by jwoLondon** [gicentre/litvis#20]
If a code block in a siding is placed between another code block and its dependency, it appears to prevent the dependent block from compiling.

This example generates the error `I cannot find a 'getValueFromBelow' variable`:

````markdown
```elm {l}
fn1 : Int
fn1 =
    getValueFromBelow
```

```elm {l siding}
fn2 : Int
fn2 =
    101
```

```elm {l}
getValueFromBelow : Int
getValueFromBelow =
    101
```
````

If the `fn2` block is not a `siding` or if it is moved to above or below the other two code blocks, there is no error.

**Comment by jwoLondon** [comment]
You are right about discussion in the draft repo - I should have remembered. What is slightly different about this case is that the blocking siding made no reference to any other block so I was surprised to see the error, but looking back at the earlier discussion I see that it is consistent with that same issue.

Do you think there is any way we can provide a more explanatory error message that is attached to siding block that is the actual cause of the problem? Or at least a hint that this might be the cause?

**Comment by kachkaev** [comment]
We can try attaching some additional text to error messages that appear in contexts other than default. So we need to decide on regexps we'll be searching for in the existing error messages and the text to append to them. Feel free to share the suggestions here.

**Comment by jwoLondon** [comment]
Closed I think we simply have to recommend people use `isolated` rather than `siding` in this context.
