### ISSUE TITLE
Parsing warning when selection name is empty

### ISSUE THREAD

**Issue by jwoLondon** [gicentre/litvis#23]
The following code is handled correctly in litvis:

```elm
selectProblem : Spec
selectProblem =
    let
        data =
            dataFromColumns []
                << dataColumn "category" (strs [ "a", "b" ])
                << dataColumn "value" (nums [ 1, 2 ])

        sel =
            selection
                << select "mySelection"
                    seSingle
                    [ seFields [ "category" ]
                    , seBind [ iSelect "category" [ inOptions [ "a", "b" ] ] ]
                    ]
    in
    toVegaLite [ sel [], circle [] ]
```

but if `iSelect "category"` is replaced with `iSelect ""` (which is valid, but not very useful), litvis generates the following parsing error in atom:

    Could not parse "{ $schema = "ht..." (litvis:expression-value)
    

Related to this, if `select "mySelection"` is replaced with `select ""` or a string with some internal whitespace (e.g. `select "my selection"`), we get a similar parsing warning. In this case, the JSON created is not a valid Vega-Lite spec, so it should be returning the error message generated by the Vega-Lite runtime (`InvalidCharacterError: The string contains invalid characters.`)

**Comment by kachkaev** [comment]
Although I've managed to fix parsing for `select ""` and `select "my selection"`, there are still hypothetical cases that will not be formatted correctly. When the value becomes an object key in JSON, it is printed without quotes in the Elm’s object string representation.

```
{ = "something" }
{ my selection = "something" }
```

If a key contains some non-alphanumerical characters, parsing becomes theoretically impossible:

```
select "="
↓
{ = = "something" }

select "\"="
↓
{ "= = "something" }

select "\"foo\" = bar"
↓
{ "foo" = bar = "something" }
```

If this becomes an issue, we should investigate how we can avoid Elm’s object string representation completely.
