### ISSUE TITLE
Problem parsing some CSV files since markdown-preview-enhanced-with-litvis v0.14.0

### ISSUE THREAD

**Issue by jwoLondon** [gicentre/litvis#27]
Possibly related to #26, data parsing of some CSV files is failing since v.0.14.0. The problem seems to be (at least) related to parsing of dates. The example below fails to parse the data from the CSV file. If encoding is limited to `AvHireTime` and `NumberOfHires` (both simple positive integer values), there is no problem. But `Month` is not read correctly. If the same data are loaded from a .json file there is no problem.

```elm
csvMonthParsing : Spec
csvMonthParsing =
    let
        data =
            --dataFromUrl "https://gicentre.github.io/data/bicycleHiresLondon.json"
            dataFromUrl "https://gicentre.github.io/data/bicycleHiresLondon.csv"

        enc =
            encoding
                << position X [ pName "Month", pMType Temporal ]
                --<< position X [ pName "AvHireTime", pMType Quantitative ]
                << position Y [ pName "NumberOfHires", pMType Quantitative ]
    in
    toVegaLite [ data [], enc [], circle [] ]
```

As with #26, a workaround is to make the code block `interactive`, which should at least help to isolate the cause of the problem.

**Comment by kachkaev** [comment]
I could not reproduce this bug after fixing #26 in https://github.com/gicentre/mume-with-litvis/commit/2233f59cca78c6efb737e117158f3ec2a500e41b. Could easily miss something, so feel free to reopen if I was too optimistic. Releasing all the recent bugfixes now.

**Comment by jwoLondon** [comment]
It looks like this issue is back again. The example above still fails. It is specific to loading temporal data from csv files. Loading from .json data files works, as does applying the .json spec in the online Vega-lite editor.

I was assuming a parsing error of some kind, but being explicit about the date format (` parse [ ( "Month", foDate "%Y-%m" ) ] `) doesn't solve the problem. As above, making the block interactive does solve it, but we shouldn't have to rely on that.

**Comment by kachkaev** [comment]
Did the error re-emerge after the recent update or was it never fixed in the first place? One possibility is that I forgot yo upgrade `vega-loader` npm dependency while updating compressed vega libraries. Can take a look this weekend.

**Comment by jwoLondon** [comment]
I am not sure if it is a re-emergence or was never fixed. I was going on your statement above that you were not able to reproduce the bug, therefore assuming that at least at one stage, the problem didn't exist. On the occasions I have tested, it has always been a problem since first spotting it.

**Comment by jwoLondon** [comment]
Here's a further example of the CSV parsing problem that does not involve dates.

Assuming a file `parsingTest.csv` is available (e.g. locally in the same folder as the litvis document) and contains the following:

```
oState,oLong,oLat,dLong,dLat
PR,-66.7,18.1,-77.3,39.4
AL,-85.8,34.4,-86.8,33.5
```

The following spec fails to filter out the `PR` value in `oState`. If the code block header is set to `interactive`, the spec works as expected.

````
```elm {v}
parsingCSVExample : Spec
parsingCSVExample =
    let
        data =
            dataFromUrl "parsingTest.csv"

        trans =
            transform << filter (fiExpr "datum.oState != 'PR'")

        enc =
            encoding
                << position Longitude [ pName "oLong", pMType Quantitative ]
                << position Latitude [ pName "oLat", pMType Quantitative ]
                << position Longitude2 [ pName "dLong" ]
                << position Latitude2 [ pName "dLat" ]
    in
    toVegaLite [ data [], trans [], rule [], enc [] ]
```
````

If instead of parsing an external .csv file, the same data are specified inline, the filtering works as expected in interactive and non-interactive modes:

```
data = 
      dataFromColumns []
            << dataColumn "oState" (strs [ "PR", "AL" ])
            << dataColumn "oLong" (nums [ -66.7, -85.8 ])
            << dataColumn "oLat" (nums [ 18.1, 34.4 ])
            << dataColumn "dLong" (nums [ -77.3, -86.8 ])
            << dataColumn "dLat" (nums [ 39.4, 33.5 ])
```

This suggests it is definitely a file parsing issue.

**Comment by jwoLondon** [comment]
Closed as the solution is to ensure .csv files do not use utf-8 with a BOM (see https://github.com/vega/vega/issues/1765)
