### ISSUE TITLE
Problems parsing field names with some non-alphanumeric characters

### ISSUE THREAD

**Issue by jwoLondon** [gicentre/litvis#29]
The following spec generates a Litvis parsing error `Could not parse "{ $schema = "ht..." (litvis:expression-value)` because the field name `a-name` contains a dash. 

```elm
barChart : Spec
barChart =
    let
        data =
            dataFromColumns []
                << dataColumn "a-name" (strs [ "A", "B", "C" ])
                << dataColumn "b" (nums [ 28, 55, 43 ])

        enc =
            encoding
                << position X [ pName "a-name", pMType Ordinal ]
                << position Y [ pName "b", pMType Quantitative ]
    in
    toVegaLite [ data [], bar [], enc [] ]
```

This is a litvis error rather than a Vega-Lite one because the equivalent JSON spec (if it could be generated by litvis) is correctly handled by the VL runtime.

**Comment by kachkaev** [comment]
This should be fixed in the next release. Not sure how much it will take me though – may not finish it today.

**Comment by kachkaev** [comment]
Looks like there's no need to wait for the Atom package release to get this through. Just uninstalling and reinstalling `markdown-preview-enhanced-with-litvis`, then reloading Atom and clearing litvis cache fixed the above example for me. This is because the dependency on `elm-string-representation` is not fixed and the patched version is downloaded by Atom when reinstalling the package.

Hope this is a useful workaround until I manage to look at another P1 and release the Atom package.

**Comment by jwoLondon** [comment]
Re-opening because while this fixes the `-` problem, it looks like it is part of a wider issue where parsing fails if a field name contains some operator symbol (e.g. fails if it includes `+`,`*`,`/`,`&`,`|`,`^` and `,`). Each of these works if encoded directly in the JSON in the Vega-Lite editor. 

I guess we need to use a more comprehensive regex for cleaning and escaping symbols.

**Comment by kachkaev** [comment]
All characters except ` = ` should be now parsable as keys. Allowing ` = ` inside keys would require  a much more sophisticated parser.

Haven't got to upgrading vega and vega lite yet, will try doing this tomorrow.

**Comment by kachkaev** [comment]
This should be released now, as well as latest vega / vega lite versions.

**Comment by jwoLondon** [comment]
It looks like fields with brackets are not being parsed correctly. 

```elm
brackets : Spec
brackets =
    let
        data =
            dataFromColumns []
                << dataColumn "speed (m/s)" (nums [ 1, 2, 3 ])

        enc =
            encoding
                << position X [ pName "speed (m/s)", pMType Quantitative ]
    in
    toVegaLite [ data [], enc [], circle [] ]
```

If you set output to `j` it appears that the brackets are being replaced with square brackets in the data specification (although interestingly not in the encoding):

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "values": [
      {
        "speed [m/s]": 1
      },
      {
        "speed [m/s]": 2
      },
      {
        "speed [m/s]": 3
      }
    ]
  },
  "encoding": {
    "x": {
      "field": "speed (m/s)",
      "type": "quantitative"
    }
  },
  "mark": "circle"
}
```

**Comment by kachkaev** [comment]
The above example works now on master (not released yet). Existing tests pass too.

> <img width="537" alt="Screenshot 2019-05-26 at 16 23 21" src="https://user-images.githubusercontent.com/608862/58383795-b51dce80-7fd2-11e9-9de9-1ec4efc80e50.png">
