### ISSUE TITLE
Allow apache arrow data loading

### ISSUE THREAD

**Issue by jwoLondon** [gicentre/litvis#31]
With the introduction of [Vega-loader-arrow](https://github.com/vega/vega-loader-arrow), it is now possible to import binary data in [apache arrow format](https://arrow.apache.org/). To do this, it requires including two extra packages, both available via npm:

https://cdn.jsdelivr.net/npm/apache-arrow
https://cdn.jsdelivr.net/npm/vega-loader-arrow

The elm-vegalite (and shortly, the elm-vega) APIs now have an `arrow` format function, so it would be good if litvis can embed the two packages to allow this to work.

Here is a vega-lite example for testing:

```elm
arrowExample : Spec
arrowExample =
    let
        pollData =
            dataFromUrl "https://gicentre.github.io/data/euPolls.arrow" [ arrow ]

        enc =
            encoding
                << position X [ pName "Answer", pMType Nominal ]
                << position Y [ pName "Percent", pMType Quantitative, pAggregate opMean ]
                << color [ mName "Pollster", mMType Nominal ]
                << column [ fName "Pollster", fMType Nominal ]
    in
    toVegaLite [ pollData, enc [], bar [] ]
```

**Comment by kachkaev** [comment]
Loading apache-arrow files should work now (https://github.com/gicentre/mume-with-litvis/commit/022fa7bc6c6434cd3fe351085a757428221949c5). Releasing new versions now.

There is a small difference between how a chart is rendered by Node.js and interactively, but I'm not sure we have control over this.

**Node.js**
> <img width="469" alt="Screenshot 2019-05-26 at 18 17 15" src="https://user-images.githubusercontent.com/608862/58385068-81e33b80-7fe2-11e9-81d1-e19015ce8798.png">

**Browser (interactive charts)**
> <img width="476" alt="Screenshot 2019-05-26 at 18 15 22" src="https://user-images.githubusercontent.com/608862/58385022-67a95d80-7fe2-11e9-88e5-e4a899ae0bb0.png">

**Comment by kachkaev** [comment]
After publishing the Atom extension I noticed this error when trying to use apache arrow data:

```
<embedded>:11 Error running script /Users/ak/.atom/packages/markdown-preview-enhanced-with-litvis/node_modules/apache-arrow/io/adapters.js
```

Could be to do with safe code execution peculiarities in Atom, needs investigation.

**Comment by kachkaev** [comment]
I opened the following example in the latest Atom plugin and it worked for me:

````md
---
id: "litvis"
elm:
    dependencies:
        gicentre/elm-vegalite: latest
---

```elm {l=hidden}
import VegaLite exposing (..)
```

# Testing Apache Arrow

```elm {v}
arrowExample : Spec
arrowExample =
    let
        pollData =
            dataFromUrl "https://gicentre.github.io/data/euPolls.arrow" [ arrow ]

        enc =
            encoding
                << position Y [ pName "Percent", pMType Quantitative, pAggregate opMean ]
                << position X [ pName "Answer", pMType Nominal ]
                << color [ mName "Pollster", mMType Nominal ]
                << column [ fName "Pollster", fMType Nominal ]
    in
    toVegaLite [ pollData, enc [], bar [] ]
```
````

Replacing ` ```elm {v} ` with ` ```elm {v i} ` also produce a chart, but I can't see any tooltips on top of it. Is it expected?

**Comment by jwoLondon** [comment]
Thanks Alex! Apache Arrow loading seems to work well now. The interactive tooltips problem is a separate (and wider) issue and I will raise this separately.
