### ISSUE TITLE
Populate the website field

### ISSUE THREAD

**Issue by jamesscottbrown** [gicentre/litvis#40]
The website field for this repository is currently empty; it would be helpful for it to be set to `https://www.gicentre.net/litvis`, as that page has useful links to the paper, slides and videos that can't otherwise be reached by following links from this repository.

**Comment by kachkaev** [comment]
Thanks for the suggestion @jamesscottbrown, please check https://github.com/gicentre/litvis. Feel free to close the issue if the change I've just made is the one you’ve meant 😉

**Comment by jamesscottbrown** [comment]
Great - that is what I meant.
