### ISSUE TITLE
Add ability to highlight lines of code

### ISSUE THREAD

**Issue by jwoLondon** [gicentre/litvis#9]
It can be helpful in a narrative to highlight arbitrary lines or blocks of code. It would be a useful feature in litvis if we could do this.

Such a feature should aim to

* allow a single line or continuous lines of code to be highlighted within a fenced code block.
* encode the highlight extent within the document itself (so not like GitHub highlighting for example)
* keep the syntax is simple as possible and readable within raw markdown
* be independent of the number of lines preceding the fenced code block
* allow external (re)styling of the code block via the normal css/less mechanism.

The best place to locate the highlight specification is probably within the curly braces of fence definition. Perhaps something like

```` ```elm {l highlight=[10-14]}````

@kachkaev Do you think this is practical?

**Comment by kachkaev** [comment]
This should be probably implemented upstrem, i.e. in mume. I opened an issue to discuss this:
https://github.com/shd101wyy/mume/issues/97

**Comment by kachkaev** [comment]
Progress on this: https://github.com/shd101wyy/mume/pull/100

**Comment by kachkaev** [comment]
https://github.com/shd101wyy/mume/pull/100 has been merged into mume's master and I cherry-picked it into our fork. The latest versions of our markdown and vscode extensions now include this feature! 🎉 

Example:

<img width="1499" alt="screenshot 2018-12-23 at 15 25 39" src="https://user-images.githubusercontent.com/608862/50385223-e57edb00-06c9-11e9-8530-07632781cbe9.png">


The styles are coming from Prism (https://prismjs.com/plugins/line-highlight/), so include line numbers by default. This is not always useful, e.g. in some of our examples the numbers overlap with the code:

<img width="699" alt="screenshot 2018-12-23 at 15 00 56" src="https://user-images.githubusercontent.com/608862/50385242-52927080-06ca-11e9-91d6-fa400cdd0d03.png">

I [patched robotoStyle.less](https://github.com/gicentre/litvis/commit/3d05a229ee40d67089c6992acf1eb521db19d301) to avoid this, but there may be other cases when a similar tweak would be needed.

<img width="700" alt="screenshot 2018-12-23 at 15 01 48" src="https://user-images.githubusercontent.com/608862/50385254-8a011d00-06ca-11e9-96c4-b3fabc38c6d7.png">

Supported syntax: https://github.com/shd101wyy/mume/issues/97#issue-377614239
